### PR TITLE
fix(android): pass the specified scope when creating configuration

### LINKED ISSUE #362: Configuration of Sign in with Apple on Android ignores scope and response type options
Currently, when configuration Sign in with Apple on Android via `appleAuthAndroid.configure` and passing a custom scope, e.g.:

```ts
appleAuthAndroid.configure({
  scope: appleAuthAndroid.Scope.EMAIL,
  // ...
});
```

That scope configuration is ignored. Instead, the Sign in with Apple request always asks the user for their email and their name, even though the name scope is not included.

Indeed, by quickly looking at the Android code, I see that [the scope is hardcoded as `SignInWithAppleConfiguration.Scope.ALL`](https://github.com/invertase/react-native-apple-authentication/blob/main/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java#L153).

Additionally, you can also notice that the response type option also appears to be ignored since [it's hardcoded as `SignInWithAppleConfiguration.ResponseType.ALL`](https://github.com/invertase/react-native-apple-authentication/blob/main/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java#L152).

So, in summary, when configuring Sign in with Apple on Android, both the `scope` and the `responseType` options are ignored, as they are just hardcoded as `ALL`.

### PR DESCRIPTION
**Pull request by MrFunctor**
Fixes #362 (except for `responseType`, which is left out as explained [here](https://github.com/invertase/react-native-apple-authentication/issues/362#issuecomment-2776387504))

### CODE REVIEW

File: android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java [hunk 1]
```diff
@@ -150,7 +150,7 @@ public void configure(ReadableMap configObject) {
             .clientId(clientId)
             .redirectUri(redirectUri)
             .responseType(SignInWithAppleConfiguration.ResponseType.ALL)
```
Comment (mikehardy) [inline android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java:152]:
```suggestion
            .responseType(responseType)
```

as long as we're in here - appears the exact same oversight happened with responseType
- it gets a default value at the top in var responseType
- the config is checked to see if it exists, and if it exists then the config value is set into responseType
- then all that is completely ignored and `ALL` is used

worth fixing? What do you think?

Comment (MrFunctor) [reply android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java:152]: I explained [here](https://github.com/invertase/react-native-apple-authentication/issues/362#issuecomment-2776387504) my reasoning related to `responseType`. Fixing it is not as simple as that...

**Review by mikehardy — APPROVED** [review]
ResponseType left alone for good reason, this is a nice focused fix for scope then

**Comment by mikehardy** [comment]
https://www.npmjs.com/package/@invertase/react-native-apple-authentication?activeTab=versions

published, thanks for the help
